name: penguins
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.1.3
  - r-tidyverse=2.0.0
  - r-rmarkdown=2.17
  - r-janitor=1.1.1
  - r-lubridate=1.9.3
  - r-here=1.0.1